# Generated by Django 3.2.8 on 2021-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diligencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=9)),
                ('fecha', models.DateField()),
                ('cualidad', models.CharField(max_length=40)),
                ('delitos', models.CharField(max_length=40)),
                ('contraparte', models.CharField(max_length=40)),
                ('k', models.CharField(max_length=40)),
                ('or_policial', models.CharField(max_length=40)),
                ('direccion_reclusion', models.CharField(max_length=40)),
                ('juzgado', models.CharField(max_length=40)),
                ('secretario', models.CharField(max_length=40)),
                ('fiscalia', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fiscal', models.CharField(max_length=80)),
                ('mp', models.CharField(max_length=80)),
                ('causa', models.CharField(max_length=80)),
                ('pronunciamiento', models.CharField(max_length=80)),
                ('sala', models.CharField(max_length=80)),
                ('decision', models.CharField(max_length=80)),
                ('ejecucion', models.CharField(max_length=80)),
                ('amparo', models.CharField(max_length=80)),
                ('casacion', models.CharField(max_length=80)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
